FROM node:alpine
WORKDIR '/app'

COPY package.json .
RUN ["/bin/sh", "-c", "npm config set proxy=http://proxy.houston.hpecorp.net:8080 && npm config set https-proxy=http://proxy.houston.hpecorp.net:8080 && npm install"]

#RUN npm install

COPY . .

CMD ["npm", "run", "start"]
